redis_url: "redis://:@localhost:6379/1"

pusher_url: ":8100"
pusher_app_id: "123456789"
pusher_app_key: "app-key"
pusher_app_secret: "app-secret"
pusher_webhook_url: "http://127.0.0.1:8080/pusher/webhook"
pusher_activity_timeout: 120
pusher_pong_timeout: 30
pusher_timestamp_grace: 600
pusher_webhook_enabled: true
